# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version: "3"
services:
  java:
    build:
      context: .
      dockerfile: infrastructure/docker/java.dockerfile
    volumes:
      - ./:/code
    working_dir: /code
    command: tail -f /dev/null
    tty: true
    ports:
      - 8999:8080
  postgres:
    image: "postgres:9.6"
    environment:
      POSTGRES_DB: beacon
      POSTGRES_USER: beacon
      POSTGRES_PASSWORD: password
