    create table if not exists info (
       id varchar(255) not null,
        created_at timestamp not null,
        updated_at timestamp not null,
        additional_location_info varchar(255),
        address varchar(255),
        beacon_id varchar(255),
        cap varchar(255),
        contact_person_email varchar(255),
        contact_person_last_name varchar(255),
        contact_person_name varchar(255),
        contact_person_organisation varchar(255),
        description_de varchar(255),
        description_en varchar(255),
        description_it varchar(255),
        latitude varchar(255),
        location varchar(255),
        longitude varchar(255),
        name_de varchar(255),
        name_en varchar(255),
        name_it varchar(255),
        website_de varchar(255),
        website_en varchar(255),
        website_it varchar(255),
        primary key (id)
    );